version: '3'

volumes:
  datafiles:
    
services:

  mysqllocal:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: parrotsays
      MYSQL_ROOT_PASSWORD: 11qq@@WW
      MYSQL_ROOT_HOST: '%'
      TZ: America/Toronto
    ports:
      - "3306:3306"

  parrotsaysapi:
    image: eduardoamparo/parrot-says-api
    restart: always
    ports:
     - 8167:8167
    depends_on:
     - mysqllocal
